config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :schools
  get 'next_school' => 'schools#next'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :school
end

app/models/school.rb
require 'csv'
class School < ActiveRecord::Base
  has_many :branches
  accepts_nested_attributes_for :branches
  #オプションを追加することもできる。編集時の削除や、limitなど

  def self.to_csv
    headers = %w(ID 学校名 学校URL 学部名 学部URL 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 学科 更新日時 作成日時)
    csv_data = CSV.generate(headers: headers, write_headers: true, force_quotes: true) do |csv|
      all.each do |row|
        csv << row.attributes.values_at(*self.column_names)
        #csv << [school.name, 'name']
      end
    end
    csv_data.encode(Encoding::SJIS)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /schools
  # GET /schools.json
  def index

    @all_school_count = School.count
    @done_school_count = School.where(:done_flg => "t").count('id')
    @schools = School.all

    respond_to do |format|
      format.html
      format.csv { send_data School.to_csv, type: 'text/csv; charset=shift_jis', filename: "school.csv" }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
    10.times {@school.branches.build}
  end

  # GET /schools/1/edit
  def edit
    (10 - @school.branches.count).times {@school.branches.build}
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: '学校を新規登録しました。' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    #render :text => "#{school_params}"
    respond_to do |format|
      if @school.update(school_params)
        @next_school = School.where(:done_flg => false).order(:id).limit(1).first
        if @next_school
          format.html { redirect_to edit_school_path(@next_school), notice: '学校・学部情報を更新しました。次の学校を表示します。' }
          format.json { render :show, status: :ok, location: @next_school }
        else
          format.html { redirect_to schools_path, notice: '学校・学部情報を更新しました。次の学校はありません。' }
          format.json { render :show, status: :ok, location: @school }
        end
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def next
    @next_school = School.where(:done_flg => false).order(:id).limit(1).first
    if @next_school
      redirect_to edit_school_path(@next_school)
    else
      redirect_to schools_path, notice: '確認が必要な学校はありません。'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :url, :done_flg, branches_attributes: [:id, :name, :url, :subject1, :subject2, :subject3, :subject4, :subject5, :subject6, :subject7, :subject8, :subject9, :subject10, :subject11, :subject12, :subject13, :subject14, :subject15, :subject16, :subject17, :subject18, :subject19, :subject20, :school_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Department</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to '学部情報収集システム', schools_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to '学部情報を入力', next_school_path %></li>
            <li><%= link_to '学校を新規登録', new_school_path %></li>
            <li><%= link_to 'CSVダウンロード', schools_path(format: 'csv') %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>　　<!-- ※この行は各ページを表示するための、最初から存在する。 -->
  </div><!-- /.container -->
</body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field school">
    <%= f.label :name, "学校名" %>
    <%= f.text_field :name %><br>
    <%= f.label :url, "サイトURL" %>
    <%= f.text_field :url, size: "60" %>
  </div>

  <hr>

  <div class="form-group">
    <%= f.fields_for :branches do |branch| %>
      <div class="field branches">
        <%= branch.label :name, "学部(大学)/学科(専門)" %>
        <%= branch.text_field :name %><br>
        <%= branch.label :url, "サイトURL" %>
        <%= branch.text_field :url, size: "60" %>
      </div>
      <div class="field subjects">
        <%= branch.label :subject1, "学科①" %>
        <%= branch.text_field :subject1 %>
        <%= branch.label :subject2, "学科②" %>
        <%= branch.text_field :subject2 %><br>
        <%= branch.label :subject3, "学科③" %>
        <%= branch.text_field :subject3 %>
        <%= branch.label :subject4, "学科④" %>
        <%= branch.text_field :subject4 %><br>
        <%= branch.label :subject5, "学科⑤" %>
        <%= branch.text_field :subject5 %>
        <%= branch.label :subject6, "学科⑥" %>
        <%= branch.text_field :subject6 %><br>
        <%= branch.label :subject7, "学科⑦" %>
        <%= branch.text_field :subject7 %>
        <%= branch.label :subject8, "学科⑧" %>
        <%= branch.text_field :subject8 %><br>
        <%= branch.label :subject9, "学科⑨" %>
        <%= branch.text_field :subject9 %>
        <%= branch.label :subject10, "学科⑩" %>
        <%= branch.text_field :subject10 %><br>
        <%= branch.label :subject11, "学科⑪" %>
        <%= branch.text_field :subject11 %>
        <%= branch.label :subject12, "学科⑫" %>
        <%= branch.text_field :subject12 %><br>
        <%= branch.label :subject13, "学科⑬" %>
        <%= branch.text_field :subject13 %>
        <%= branch.label :subject14, "学科⑭" %>
        <%= branch.text_field :subject14 %><br>
        <%= branch.label :subject15, "学科⑮" %>
        <%= branch.text_field :subject15 %>
        <%= branch.label :subject16, "学科⑯" %>
        <%= branch.text_field :subject16 %><br>
        <%= branch.label :subject17, "学科⑰" %>
        <%= branch.text_field :subject17 %>
        <%= branch.label :subject18, "学科⑱" %>
        <%= branch.text_field :subject18 %><br>
        <%= branch.label :subject19, "学科⑲" %>
        <%= branch.text_field :subject19 %>
        <%= branch.label :subject20, "学科⑳" %>
        <%= branch.text_field :subject20 %>
      </div>
      <hr>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit '更新する', class: 'btn-default',data: {disable_with: '作成中…'} %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h4><%= @school.name %> <%= link_to '（リンクを開く）', @school.url, :target=>["school_page"] %></h4>
</div>

<%= render 'form' %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h4>登録済みの学校一覧 [ 完了 ： <%= @done_school_count %>校 / <%= @all_school_count %>校 ]</h4>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>学校名（学校名をクリックして編集）</th>
      <th>学校URL</th>
      <th>確認済</th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to school.name, edit_school_path(school) %></td>
        <td><%= link_to school.url, school.url, :target=>["_blank"] %></td>
        <td><%= school.done_flg %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @school.url %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>